# Numpy - numerical python

-> in datascience arrays are handled by library called numpy
-> its a library which handles multi dimensional array 1d,2d,3d ... nd array(more than 3 rows)
-> numpy used to build all the models , machine learning , deep learning , gen AI , Agentic AI

# uses of numpy
->arithemetic operations
->statistic operations
-> bitwise operation
-> copy an dbit array
->stacking
-> matrix operation
->linear algebra
->broadcasting
->math operation
->searching , sorting ,counting

# important point
->numpy built on data structures, math ,stats,array
->it has 217 built in function
->used for structured and unstructured data



In [3]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
#convert list to array
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [5]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
#217 functionalities inside numpy 


In [7]:
np.arange(10) #inerval between 0 -10,user passes arguments 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [9]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [11]:
np.arange(10,5) #1st arg should be less than 2nd

array([], dtype=int32)

In [12]:
np.arange(-10,5)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4])

In [13]:
np.arange(1,100,5,3)  #arange takes only 3 arguments

TypeError: Cannot interpret '3' as a data type

# Zeros()
-> defaultly system captures float 

In [14]:
np.zeros(3)  #parameter tuning

array([0., 0., 0.])

In [15]:
np.zeros(3, dtype =int) #hyperparameter tuning

array([0, 0, 0])

In [17]:
np.zeros((2,2))  #2d array

array([[0., 0.],
       [0., 0.]])

In [19]:
np.zeros((2,2) , dtype = int)

array([[0, 0],
       [0, 0]])

In [20]:
np.zeros((5,10) , dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [22]:
np.ones((2,6 ),dtype = int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

# Rand()

->for OTP generations
-> random number it gives everytime

In [23]:
rand(2,3)

NameError: name 'rand' is not defined

In [24]:
random.rand(2,3)

NameError: name 'random' is not defined

In [26]:
np.random.rand(2,3)

array([[0.49041542, 0.59642516, 0.66638741],
       [0.00306027, 0.73580028, 0.28520211]])

In [33]:
np.random.randint(2,9)

6

In [36]:
np.random.randint(1,20,4)

array([13,  1, 11,  6])

In [39]:
np.random.randint(10,40,(10,10)) #10rows ,10 colums it gies 10 to 40 numbers

array([[12, 16, 23, 31, 22, 39, 30, 32, 11, 18],
       [16, 23, 21, 14, 23, 21, 27, 19, 15, 33],
       [24, 11, 25, 23, 10, 15, 23, 12, 31, 33],
       [24, 37, 17, 31, 21, 39, 13, 38, 15, 20],
       [16, 37, 14, 10, 11, 37, 36, 22, 24, 28],
       [32, 17, 28, 19, 38, 21, 27, 39, 34, 22],
       [30, 29, 19, 27, 38, 25, 10, 25, 22, 19],
       [34, 28, 24, 31, 33, 18, 35, 13, 14, 23],
       [29, 19, 13, 27, 23, 23, 27, 18, 14, 14],
       [13, 10, 17, 14, 34, 11, 32, 19, 11, 17]])

In [40]:
a = np.random.randint(10,40,(10,10))
print(a)

[[29 38 30 23 20 34 28 26 21 14]
 [27 17 19 37 28 36 32 24 23 37]
 [13 19 11 31 15 38 39 25 38 32]
 [10 19 11 16 33 29 21 11 12 34]
 [19 19 19 19 36 34 25 26 36 25]
 [27 14 19 35 37 13 34 25 28 36]
 [28 30 27 36 28 26 35 31 12 32]
 [19 21 22 31 29 27 21 20 25 21]
 [38 15 38 31 25 13 23 28 36 23]
 [25 34 30 38 30 15 10 39 33 25]]


# reshaping 

->after arrange to shape that array in different manner it gives output


In [41]:
np.arange(1,13).reshape(3,4)  # between the mentioned intervals in arrange , shape it as 3*4 matrix , it should be within the range

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
np.arange(1,13).reshape(4,4)  # 4 * 4 -16 so it doesn't give output exceeds the value 

ValueError: cannot reshape array of size 12 into shape (4,4)

# Slicing and indexing  in matrix

In [4]:
b = np.random.randint(10,20,(5,4))
b

array([[15, 16, 16, 10],
       [12, 10, 17, 18],
       [19, 16, 10, 14],
       [10, 19, 18, 10],
       [15, 12, 13, 18]])

In [5]:
type(b)

numpy.ndarray

In [6]:
b[:] #slicing it prints rows

array([[15, 16, 16, 10],
       [12, 10, 17, 18],
       [19, 16, 10, 14],
       [10, 19, 18, 10],
       [15, 12, 13, 18]])

In [7]:
b[1:3]

array([[12, 10, 17, 18],
       [19, 16, 10, 14]])

In [8]:
b

array([[15, 16, 16, 10],
       [12, 10, 17, 18],
       [19, 16, 10, 14],
       [10, 19, 18, 10],
       [15, 12, 13, 18]])

In [9]:
b[1,3] #it gives value

18

In [10]:
b[::-1]

array([[15, 12, 13, 18],
       [10, 19, 18, 10],
       [19, 16, 10, 14],
       [12, 10, 17, 18],
       [15, 16, 16, 10]])

In [11]:
b [::-2]

array([[15, 12, 13, 18],
       [19, 16, 10, 14],
       [15, 16, 16, 10]])

In [12]:
b[::-3]

array([[15, 12, 13, 18],
       [12, 10, 17, 18]])

In [13]:
b[::3]

array([[15, 16, 16, 10],
       [10, 19, 18, 10]])

# indexing in array

In [15]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [20]:
row, column = (4,5)


In [21]:
print(row)
print(column)

4
5


In [22]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [24]:
mat [row,column]

45

In [25]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
#how to print rows

In [26]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
mat[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
mat[-9]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
mat[0:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [ ]:
#how to print column

In [30]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
mat [:,0] #slice to print columns

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [33]:
mat[0]  #to print columns

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [37]:
mat[:,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [12, 13, 14, 15, 16, 17],
       [22, 23, 24, 25, 26, 27],
       [32, 33, 34, 35, 36, 37],
       [42, 43, 44, 45, 46, 47],
       [52, 53, 54, 55, 56, 57],
       [62, 63, 64, 65, 66, 67],
       [72, 73, 74, 75, 76, 77],
       [82, 83, 84, 85, 86, 87],
       [92, 93, 94, 95, 96, 97]])

In [39]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [38]:
mat [2:6 ,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [40]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [41]:
mat[1:6 , 1:6]

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45],
       [51, 52, 53, 54, 55]])

In [42]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [44]:
mat[:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [46]:
mat[:,0:10:3]

array([[ 0,  3,  6,  9],
       [10, 13, 16, 19],
       [20, 23, 26, 29],
       [30, 33, 36, 39],
       [40, 43, 46, 49],
       [50, 53, 56, 59],
       [60, 63, 66, 69],
       [70, 73, 76, 79],
       [80, 83, 86, 89],
       [90, 93, 96, 99]])

In [48]:
mat[0,9]

9

# masking or filtering


In [50]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [51]:
id(mat)

2005329332144

In [ ]:
#constructor  - special method - in memory management 
__init__

In [52]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [53]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [55]:
mat [mat < 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [56]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [59]:
mat [mat >= 50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [61]:
mat [mat == 50]

array([50])